### ISSUE TITLE
Trojan:Win32/Phonzy.C!ml - "WinThumbsPreloader 2.0.0 Beta 2"

### ISSUE THREAD

**Issue by OSHM34** [Mfarooq360/WinThumbsPreloader-V2#6]
Hi,
I just wanted to download "WinThumbsPreloader 2.0.0 Beta 2" from https://github.com/Mfarooq360/WinThumbsPreloader-V2/releases/download/v2.0.0-beta2/WinThumbsPreloader-2.0.0-setup.exe

Windows Security blocked the download and reported that the file is infected with "Trojan:Win32/Phonzy.C!ml"

Please see the attached screenshots.

Is that a bug or some serious threat? 

![Screenshot 2023-12-03 112838](https://github.com/Mfarooq360/WinThumbsPreloader-V2/assets/91694003/755224d9-cbbb-4b75-b3bc-3b481b056b9d)
![Screenshot 2023-12-03 113114](https://github.com/Mfarooq360/WinThumbsPreloader-V2/assets/91694003/9bacb761-09e6-4ef7-b408-a35ca951a1ea)
![Screenshot 2023-12-03 113642](https://github.com/Mfarooq360/WinThumbsPreloader-V2/assets/91694003/319385ae-3c39-4dcd-8586-6d35b2616604)
![Screenshot 2023-12-03 113753](https://github.com/Mfarooq360/WinThumbsPreloader-V2/assets/91694003/a871abb6-8b7d-45d2-8fe1-1160d0b4f598)

Kind regards,
Hakan
[Copy pasted text from Windows Security Threat details.txt](https://github.com/Mfarooq360/WinThumbsPreloader-V2/files/13538814/Copy.pasted.text.from.Windows.Security.Threat.details.txt)

**Comment by VL4DST3R** [comment]
Highly doubt there's anything more than a false positive, but give the portable version a try, it requires no installation.

**Comment by Mfarooq360** [comment]
Turns out the setup version of WinThumbsPreloader has a higher amount of false positives than the portable version based on VirusTotal, the new beta 3 that I put out initially had a Windows Defender detection but now states that it cleared so hopefully it shouldn't trigger Windows Defender, at least on beta 3. 

I'm not entirely sure what's specifically triggering the detections, though I have noticed this issue being mentioned in the issues of the original fork of this program from the original author, so most likely the setup file's modification of the registry and inclusion of dlls such as the task scheduler dll probably makes it trigger the false positives.

Beta 2:
![image](https://github.com/Mfarooq360/WinThumbsPreloader-V2/assets/97059075/bc9a8b71-71e0-4d08-b6f2-d3962c258618)

Beta 3:
![image](https://github.com/Mfarooq360/WinThumbsPreloader-V2/assets/97059075/e98f8930-ecbe-44df-ad46-d929ce847a79)

Portable version of Beta 3:
![image](https://github.com/Mfarooq360/WinThumbsPreloader-V2/assets/97059075/f8f214e2-5fb2-44a3-beaf-95e978c85ecc)

**Comment by VL4DST3R** [comment]
Considering the relatively new and exotic nature of this tool false positives like this will pop up from time to time. If anyone has any doubts about the behavior of the program then feel free to peruse the code or compile it for yourself. Will close this for now."
